### ISSUE TITLE
Cannot submit new app due to incorrect email validation

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#172]
@uclanate I'm submitting a new app to test the editing later on but I cannot submit new one, the app is prompting me that primary contact email is missing but the email is already entered. See below:
![image](https://user-images.githubusercontent.com/1034174/49603752-f9dc7d00-f940-11e8-9610-08052fced488.png)

**Comment by uclanate** [comment]
I believe this is fixed with commit  0e6833f

**Comment by ctrance** [comment]
@uclanate Still not fixed, I also made sure that staging has the latest commit by appending status.json.

![image](https://user-images.githubusercontent.com/1034174/49666180-11346c80-fa0c-11e8-98e7-8a57d681e740.png)

**Comment by uclanate** [comment]
OK this is fixed now. @ctrance please double check for me, and then we can close this

**Comment by ctrance** [comment]
Fixed now, thanks @uclanate!
